name: Protect main branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Skip if admin token secret not set
        if: ${{ secrets.REPO_ADMIN_TOKEN == '' }}
        run: |
          echo "REPO_ADMIN_TOKEN not set; skipping branch protection configuration."

      - name: Apply branch protection settings
        if: ${{ secrets.REPO_ADMIN_TOKEN != '' }}
        env:
          GH_TOKEN: ${{ secrets.REPO_ADMIN_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: main
        run: |
          set -euo pipefail
          echo "Configuring protection for $REPO@$BRANCH"
          curl -sS -X PUT "https://api.github.com/repos/$REPO/branches/$BRANCH/protection" \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{
                  "required_status_checks": null,
                  "enforce_admins": true,
                  "required_pull_request_reviews": {
                    "dismiss_stale_reviews": true,
                    "require_code_owner_reviews": true,
                    "required_approving_review_count": 1
                  },
                  "restrictions": null,
                  "allow_force_pushes": false,
                  "allow_deletions": false,
                  "required_linear_history": true,
                  "required_conversation_resolution": true
                }'

      - name: Require signed commits
        if: ${{ secrets.REPO_ADMIN_TOKEN != '' }}
        env:
          GH_TOKEN: ${{ secrets.REPO_ADMIN_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: main
        run: |
          set -euo pipefail
          curl -sS -X POST "https://api.github.com/repos/$REPO/branches/$BRANCH/protection/required_signatures" \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28"

